/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VrRouteImport } from './routes/vr'
import { Route as TeoricaRouteImport } from './routes/teorica'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PraticaRouteImport } from './routes/pratica'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeoricaIndexRouteImport } from './routes/teorica.index'
import { Route as PraticaIndexRouteImport } from './routes/pratica.index'
import { Route as TeoricaSlugRouteImport } from './routes/teorica.$slug'
import { Route as PraticaSlugRouteImport } from './routes/pratica.$slug'

const VrRoute = VrRouteImport.update({
  id: '/vr',
  path: '/vr',
  getParentRoute: () => rootRouteImport,
} as any)
const TeoricaRoute = TeoricaRouteImport.update({
  id: '/teorica',
  path: '/teorica',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticaRoute = PraticaRouteImport.update({
  id: '/pratica',
  path: '/pratica',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeoricaIndexRoute = TeoricaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeoricaRoute,
} as any)
const PraticaIndexRoute = PraticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PraticaRoute,
} as any)
const TeoricaSlugRoute = TeoricaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeoricaRoute,
} as any)
const PraticaSlugRoute = PraticaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PraticaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pratica': typeof PraticaRouteWithChildren
  '/quiz': typeof QuizRoute
  '/sobre': typeof SobreRoute
  '/teorica': typeof TeoricaRouteWithChildren
  '/vr': typeof VrRoute
  '/pratica/$slug': typeof PraticaSlugRoute
  '/teorica/$slug': typeof TeoricaSlugRoute
  '/pratica/': typeof PraticaIndexRoute
  '/teorica/': typeof TeoricaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/sobre': typeof SobreRoute
  '/vr': typeof VrRoute
  '/pratica/$slug': typeof PraticaSlugRoute
  '/teorica/$slug': typeof TeoricaSlugRoute
  '/pratica': typeof PraticaIndexRoute
  '/teorica': typeof TeoricaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pratica': typeof PraticaRouteWithChildren
  '/quiz': typeof QuizRoute
  '/sobre': typeof SobreRoute
  '/teorica': typeof TeoricaRouteWithChildren
  '/vr': typeof VrRoute
  '/pratica/$slug': typeof PraticaSlugRoute
  '/teorica/$slug': typeof TeoricaSlugRoute
  '/pratica/': typeof PraticaIndexRoute
  '/teorica/': typeof TeoricaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pratica'
    | '/quiz'
    | '/sobre'
    | '/teorica'
    | '/vr'
    | '/pratica/$slug'
    | '/teorica/$slug'
    | '/pratica/'
    | '/teorica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/quiz'
    | '/sobre'
    | '/vr'
    | '/pratica/$slug'
    | '/teorica/$slug'
    | '/pratica'
    | '/teorica'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pratica'
    | '/quiz'
    | '/sobre'
    | '/teorica'
    | '/vr'
    | '/pratica/$slug'
    | '/teorica/$slug'
    | '/pratica/'
    | '/teorica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PraticaRoute: typeof PraticaRouteWithChildren
  QuizRoute: typeof QuizRoute
  SobreRoute: typeof SobreRoute
  TeoricaRoute: typeof TeoricaRouteWithChildren
  VrRoute: typeof VrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vr': {
      id: '/vr'
      path: '/vr'
      fullPath: '/vr'
      preLoaderRoute: typeof VrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teorica': {
      id: '/teorica'
      path: '/teorica'
      fullPath: '/teorica'
      preLoaderRoute: typeof TeoricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratica': {
      id: '/pratica'
      path: '/pratica'
      fullPath: '/pratica'
      preLoaderRoute: typeof PraticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teorica/': {
      id: '/teorica/'
      path: '/'
      fullPath: '/teorica/'
      preLoaderRoute: typeof TeoricaIndexRouteImport
      parentRoute: typeof TeoricaRoute
    }
    '/pratica/': {
      id: '/pratica/'
      path: '/'
      fullPath: '/pratica/'
      preLoaderRoute: typeof PraticaIndexRouteImport
      parentRoute: typeof PraticaRoute
    }
    '/teorica/$slug': {
      id: '/teorica/$slug'
      path: '/$slug'
      fullPath: '/teorica/$slug'
      preLoaderRoute: typeof TeoricaSlugRouteImport
      parentRoute: typeof TeoricaRoute
    }
    '/pratica/$slug': {
      id: '/pratica/$slug'
      path: '/$slug'
      fullPath: '/pratica/$slug'
      preLoaderRoute: typeof PraticaSlugRouteImport
      parentRoute: typeof PraticaRoute
    }
  }
}

interface PraticaRouteChildren {
  PraticaSlugRoute: typeof PraticaSlugRoute
  PraticaIndexRoute: typeof PraticaIndexRoute
}

const PraticaRouteChildren: PraticaRouteChildren = {
  PraticaSlugRoute: PraticaSlugRoute,
  PraticaIndexRoute: PraticaIndexRoute,
}

const PraticaRouteWithChildren =
  PraticaRoute._addFileChildren(PraticaRouteChildren)

interface TeoricaRouteChildren {
  TeoricaSlugRoute: typeof TeoricaSlugRoute
  TeoricaIndexRoute: typeof TeoricaIndexRoute
}

const TeoricaRouteChildren: TeoricaRouteChildren = {
  TeoricaSlugRoute: TeoricaSlugRoute,
  TeoricaIndexRoute: TeoricaIndexRoute,
}

const TeoricaRouteWithChildren =
  TeoricaRoute._addFileChildren(TeoricaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PraticaRoute: PraticaRouteWithChildren,
  QuizRoute: QuizRoute,
  SobreRoute: SobreRoute,
  TeoricaRoute: TeoricaRouteWithChildren,
  VrRoute: VrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
